### ISSUE TITLE
Support for functions?

### ISSUE THREAD

**Issue by dantleech** [fenetikm/autoload-drupal#1]
This works great for classes and Phpactor :)

I also tried using it with [PHPStan](https://github.com/phpstan/phpstan) but it seems none of the functions are found:

```
------ --------------------------------------------------------------                                          
  Line   docroot/modules/custom/astra_site/src/Form/NodeFormAlter.php                                           
 ------ --------------------------------------------------------------                                          
  50     Function menu_ui_get_menu_link_defaults not found.                                                     
  59     Function t not found.                                                                                  
  68     Function menu_ui_get_menus not found.                                                                  
 ------ --------------------------------------------------------------                                          
```

Not really sure if anything can be done here - I guess maybe adding the `.module` files to composer?

**Comment by DieterHolvoet** [comment]
I worked around that issue by adding the files to the PHPStan config:
```yaml
parameters:
    autoload_files:
        - vendor/drupal/core/includes/bootstrap.inc
        - vendor/drupal/core/modules/system/system.module
```
